### ISSUE TITLE
video upload issue please help

### ISSUE THREAD

**Issue by absolute-chad** [pierreminiggio/instagram-story-poster#1]
![Screenshot 2021-11-12 134402](https://user-images.githubusercontent.com/94161290/141433425-fbe06e25-9dc6-4413-9022-b3ace2e867f8.png)

terminal error:

[mov,mp4,m4a,3gp,3g2,mj2 @ 00000182e53bdcc0] moov atom not foundvideos\aHR0cHM6Ly95b3V0dS5iZS9uX1Z5V19VY05OYw==.mp4: Invalid data found when processing inputTraceback (most recent call last):
  File "main.py", line 21, in <module>
    videos_to_upload = build_videos_to_upload(video_url, video_path)  File "C:\Users\shrim\Downloads\instagram-story-poster-main\instagram-story-poster-main\build_videos_to_upload.py", line 10, in build_videos_to_upload
    duration = get_video_duration(video_path)  File "C:\Users\shrim\Downloads\instagram-story-poster-main\instagram-story-poster-main\get_video_duration.py", line 9, in get_video_duration
    return float(duration_command_output)
ValueError: could not convert string to float: PS C:\Users\shrim\Downloads\instagram-story-poster-main\instagram-story-poster-main>

**Comment by pierreminiggio** [comment]
the "video_url" parameter requires an actual video_file URL, not a Youtube video link.
Example : https://storage.miniggiodev.fr/test/story.mp4
